### PR TITLE
Revert "Rebuild for python311"

### PR DESCRIPTION
**Pull request by alenaizan**
This is the same pull request as #5 but from a personal fork. There are issues in the MacOS build as mentioned in #5

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
Please do not revert gh-4.
All builds apart from the `osx-64` ones seem to be fine (even the 3.11 ones).
Since all `osx-64` builds (Python 3.11 or not) are affected, this should either skip `osx` or, ideally, receive fixes upstream.

**Comment by alenaizan** [comment]
I will close this PR and try to work on fixing the OSX platform at some point.

**Comment by mbargull** [comment]
Thanks.
Please make sure to include https://github.com/conda-forge/pnab-feedstock/pull/6/commits/b101b54da9dfae823cb0a489aad847158caf237f for future builds to catch the failing tests (to avoid publishing broken builds).
You can see at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=608526&view=results that `osx-64` "expectedly fails" with that.

**Pull request closed without merging**
